// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/redacted.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRedactedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId             int64 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	RedactedClusterId int64 `protobuf:"varint,2,opt,name=Redacted_cluster_id,json=RedactedClusterId,proto3" json:"Redacted_cluster_id,omitempty"`
	Replicas          int64 `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *CreateRedactedRequest) Reset() {
	*x = CreateRedactedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_redacted_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRedactedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRedactedRequest) ProtoMessage() {}

func (x *CreateRedactedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redacted_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRedactedRequest.ProtoReflect.Descriptor instead.
func (*CreateRedactedRequest) Descriptor() ([]byte, []int) {
	return file_proto_redacted_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRedactedRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *CreateRedactedRequest) GetRedactedClusterId() int64 {
	if x != nil {
		return x.RedactedClusterId
	}
	return 0
}

func (x *CreateRedactedRequest) GetReplicas() int64 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type CreateRedactedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status            string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	OrgId             int64  `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	RedactedClusterId int64  `protobuf:"varint,3,opt,name=Redacted_cluster_id,json=RedactedClusterId,proto3" json:"Redacted_cluster_id,omitempty"`
}

func (x *CreateRedactedResponse) Reset() {
	*x = CreateRedactedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_redacted_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRedactedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRedactedResponse) ProtoMessage() {}

func (x *CreateRedactedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redacted_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRedactedResponse.ProtoReflect.Descriptor instead.
func (*CreateRedactedResponse) Descriptor() ([]byte, []int) {
	return file_proto_redacted_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRedactedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRedactedResponse) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *CreateRedactedResponse) GetRedactedClusterId() int64 {
	if x != nil {
		return x.RedactedClusterId
	}
	return 0
}

type DeleteRedactedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId             int64 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	RedactedClusterId int64 `protobuf:"varint,2,opt,name=Redacted_cluster_id,json=RedactedClusterId,proto3" json:"Redacted_cluster_id,omitempty"`
}

func (x *DeleteRedactedRequest) Reset() {
	*x = DeleteRedactedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_redacted_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRedactedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRedactedRequest) ProtoMessage() {}

func (x *DeleteRedactedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redacted_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRedactedRequest.ProtoReflect.Descriptor instead.
func (*DeleteRedactedRequest) Descriptor() ([]byte, []int) {
	return file_proto_redacted_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRedactedRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *DeleteRedactedRequest) GetRedactedClusterId() int64 {
	if x != nil {
		return x.RedactedClusterId
	}
	return 0
}

type DeleteRedactedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status            string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	OrgId             int64  `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	RedactedClusterId int64  `protobuf:"varint,3,opt,name=Redacted_cluster_id,json=RedactedClusterId,proto3" json:"Redacted_cluster_id,omitempty"`
}

func (x *DeleteRedactedResponse) Reset() {
	*x = DeleteRedactedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_redacted_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRedactedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRedactedResponse) ProtoMessage() {}

func (x *DeleteRedactedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redacted_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRedactedResponse.ProtoReflect.Descriptor instead.
func (*DeleteRedactedResponse) Descriptor() ([]byte, []int) {
	return file_proto_redacted_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRedactedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteRedactedResponse) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *DeleteRedactedResponse) GetRedactedClusterId() int64 {
	if x != nil {
		return x.RedactedClusterId
	}
	return 0
}

var File_proto_redacted_proto protoreflect.FileDescriptor

var file_proto_redacted_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a,
	0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x2e, 0x0a,
	0x13, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x52, 0x65, 0x64, 0x61,
	0x63, 0x74, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x77, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6f,
	0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x11, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x5e, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x64, 0x61,
	0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6f,
	0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x11, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x77, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x64, 0x61,
	0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x52,
	0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74,
	0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x32, 0xac, 0x01, 0x0a, 0x08,
	0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x12, 0x4f, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_redacted_proto_rawDescOnce sync.Once
	file_proto_redacted_proto_rawDescData = file_proto_redacted_proto_rawDesc
)

func file_proto_redacted_proto_rawDescGZIP() []byte {
	file_proto_redacted_proto_rawDescOnce.Do(func() {
		file_proto_redacted_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_redacted_proto_rawDescData)
	})
	return file_proto_redacted_proto_rawDescData
}

var file_proto_redacted_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_redacted_proto_goTypes = []interface{}{
	(*CreateRedactedRequest)(nil),  // 0: proto.CreateRedactedRequest
	(*CreateRedactedResponse)(nil), // 1: proto.CreateRedactedResponse
	(*DeleteRedactedRequest)(nil),  // 2: proto.DeleteRedactedRequest
	(*DeleteRedactedResponse)(nil), // 3: proto.DeleteRedactedResponse
}
var file_proto_redacted_proto_depIdxs = []int32{
	0, // 0: proto.Redacted.CreateRedacted:input_type -> proto.CreateRedactedRequest
	2, // 1: proto.Redacted.DeleteRedacted:input_type -> proto.DeleteRedactedRequest
	1, // 2: proto.Redacted.CreateRedacted:output_type -> proto.CreateRedactedResponse
	3, // 3: proto.Redacted.DeleteRedacted:output_type -> proto.DeleteRedactedResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_redacted_proto_init() }
func file_proto_redacted_proto_init() {
	if File_proto_redacted_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_redacted_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRedactedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_redacted_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRedactedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_redacted_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRedactedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_redacted_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRedactedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_redacted_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_redacted_proto_goTypes,
		DependencyIndexes: file_proto_redacted_proto_depIdxs,
		MessageInfos:      file_proto_redacted_proto_msgTypes,
	}.Build()
	File_proto_redacted_proto = out.File
	file_proto_redacted_proto_rawDesc = nil
	file_proto_redacted_proto_goTypes = nil
	file_proto_redacted_proto_depIdxs = nil
}
